import Navbar from "@/components/shared/navbar/Navbar"
import './globals.css'

export const metadata = {
  title: 'Info Rover',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  )
}
